
//DOM --Document Object model generated by HTML--->
//DOM---->is an API interface provided by browser--->once web page is loaded -->
//HTML---> inspect ->view pagesource ->html+js
//Locator -Identifies locator in the page in the DOM

// page.getByRole() to locate by explicit and implicit accessibility attributes.
// page.getByText() to locate by text content.
// page.getByLabel() to locate a form control by associated label's text.
// page.getByPlaceholder() to locate an input by placeholder.
// page.getByAltText() to locate an element, usually image, by its text alternative.
// page.getByTitle() to locate an element by its title attribute.
// page.getByTestId() to locate an element based on its data-testid attribute (other attributes can be configured).

import {test,expect,Locator} from "@playwright/test"

test("verify playwright Locators", async ({page})=>{


    await page.goto("https://demo.nopcommerce.com/");

//page.getByAltText()
    const text:Locator = page.getByAltText("nopCommerce demo store");
await expect(text).toBeVisible();

//page.getByText() --used for String ,substring, partial text

await expect(page.getByText("Welcome to our store")).toBeVisible();
await expect(page.getByText("Welcome to")).toBeVisible();
await expect(page.getByText(/Welcome\s+To\s+Our\s+Store/i)).toBeVisible(); //i ---to make case insensitive /s-space --regular expression

//page.getByRole() -- for implicit and explicit define role ----button, heading,textbox,links

await page.getByRole("link", {name: 'Register'}).click(); //explicit define role ---where tag name and role name are diff
await page.getByRole("heading",{name:'Welcome to our store'}).click();





});